// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.19.6
// source: proto/wallet.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'wallet';

export interface CreateWalletRequest {
  userId: string;
}

export interface GetWalletRequest {
  userId: string;
}

export interface CreditWalletRequest {
  userId: string;
  /**
   * I send the amount as a string to preserve decimal precision (e.g. "500.00")
   * Using a float or double may introduce rounding errors end
   * As such I will parse as a decimal on the receiver's end
   */
  amount: string;
}

export interface DebitWalletRequest {
  userId: string;
  amount: string;
}

export interface WalletResponse {
  id: string;
  userId: string;
  /**
   * I do the same here
   * I convert the balance to a string to avoid precision loss from float or double
   */
  balance: string;
  createdAt: string;
}

export const WALLET_PACKAGE_NAME = 'wallet';

export interface WalletServiceClient {
  createWallet(request: CreateWalletRequest): Observable<WalletResponse>;

  getWallet(request: GetWalletRequest): Observable<WalletResponse>;

  creditWallet(request: CreditWalletRequest): Observable<WalletResponse>;

  debitWallet(request: DebitWalletRequest): Observable<WalletResponse>;
}

export interface WalletServiceController {
  createWallet(
    request: CreateWalletRequest,
  ): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  getWallet(
    request: GetWalletRequest,
  ): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  creditWallet(
    request: CreditWalletRequest,
  ): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;

  debitWallet(
    request: DebitWalletRequest,
  ): Promise<WalletResponse> | Observable<WalletResponse> | WalletResponse;
}

export function WalletServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createWallet',
      'getWallet',
      'creditWallet',
      'debitWallet',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('WalletService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('WalletService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const WALLET_SERVICE_NAME = 'WalletService';
